version: '3.8'

services:
  mongo-db:
    image: mongo:6.0.13
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}  ##usaremos nuestras variables de entorno
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - ./mongo:/data/db ##Significa que la base de datos de mongo se genere en este mismo proyecto
    ports:
      - 27017:27017 ##Pondremos el mismo puerto interno de docker que el de mongo db (el de la derecha es el puerto de MONGO y el de la izquierda el disponible en mi ordenador para usarlo)
      